# 
# Global rules

debug = false
#logLevel = "DEBUG"
logLevel = "INFO"
#traefikLogsFile = "/opt/traefik/log/traefik.log"
#accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]
#defaultEntryPoints = ["https"]
[entryPoints]
 [entryPoints.http]
 address = ":80"
  #[entryPoints.http.redirect]
   #entryPoint = "https"
 [entryPoints.https]
 address = ":443"
 [entryPoints.https.tls]
   [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/certs/leveraging.com.crt"
    KeyFile  = "/etc/ssl/certs/leveraging.com.key"

#
# Web Admin tool

[web]
 address = ":8080"


#
# Docker support

[docker]
 domain = "leveraging.com"
 watch = true


#
# Manual Routes

[file]
[backends]

#
# Test endpoint
# [backends.test-backend]
# [backends.test-backend.servers.server1]
#  url = "https://www.google.com/"

#
# APIC API endpoint into datapower
# [backends.apic-docker]
# [backends.apic-docker.servers.server1]
#  url = "https://datapower:443"



[frontends]
#
# Test endpoint
# [frontends.test]
# backend = "test-backend"
# passHostHeader = true
# #entrypoints = ["http","https"]
# [frontends.test.routes.default]
#  rule = "Host:test.leveraging.com"

#
# APIC API endpoint into datapower
# [frontends.apic-docker]
# backend = "apic-docker"
# passHostHeader = true
# entrypoints = ["https"]
# [frontends.apic-docker.routes.default]
#  rule = "Host:apic-docker.leverging.com"

