#
# Global rules

debug = false
#logLevel = "DEBUG"
logLevel = "INFO"
#traefikLogsFile = "/opt/traefik/log/traefik.log"
#accessLogsFile = "/opt/traefik/log/access.log"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]
#defaultEntryPoints = ["https"]
[entryPoints]
 [entryPoints.http]
 address = ":80"
  #[entryPoints.http.redirect]
   #entryPoint = "https"
 [entryPoints.https]
 address = ":443"
 [entryPoints.https.tls]
   [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/ssl/certs/hcc.org.crt"
    KeyFile  = "/etc/ssl/certs/hcc.org.key"

#
# Web Admin tool

[web]
 address = ":8080"
# CertFile = "/etc/ssl/certs/hcc.org.crt"
# KeyFIle = "hcc.org.key"


#
# Docker support

[docker]
 domain = "hcc.org"
 watch = true


#
# Manual Routes

[file]
[backends]

#
# Test endpoint
 [backends.test-backend]
 [backends.test-backend.servers.server1]
  url = "https://www.google.com/"

#
# Trafik static endpoint to bypass the RPS on 80/443
 [backends.traefik-docker-admin]
 [backends.traefik-docker-admin.servers.server1]
  url = "http://172.17.0.2:8080"
  #url = "http://traefik:8080"
  #url = "http://ad9535a61f27:8080"
  #url = "http://traefik.hcc.org:8080"
  #url = "http://localhost:8080"

#
# APIC API endpoint into datapower
 [backends.apic-docker]
 [backends.apic-docker.servers.server1]
  url = "https://datapower:443"


[frontends]
#
# Test endpoint
 [frontends.test]
 backend = "test-backend"
 passHostHeader = true
 #entrypoints = ["http","https"]
 [frontends.test.routes.default]
  rule = "Host:test.hcc.org"

#
# Trafik static endpoint to bypass the RPS on 80/443
 [frontends.traefik]
 backend = "traefik-docker-admin"
 passHostHeader = true
 [frontends.traefik.routes.default]
  rule = "Host:traefik.hcc.org"

#
# APIC API endpoint into datapower
 [frontends.apic-docker]
 backend = "apic-docker"
 passHostHeader = true
 entrypoints = ["https"]
 [frontends.apic-docker.routes.default]
  rule = "Host:apic-docker.hcc.org"

